### ISSUE TITLE
python3 compatible? requirements?

### ISSUE THREAD

**Issue by ruxi** [flo-compbio/pyaffy#10]
Is this a python 3 compatible package?

Got an error: missing module urllib2. 

Not sure if its an one-off thing that can be fixed by adding the lib to requirements.txt, or if this package was developed from the ground up in python 2.

**Comment by flo-compbio** [comment]
Hi, I think the code in this package doesn't require modifications to run under Python 3, but currently the package depends on an old version of another package of mine (genometools) that maybe doesn't support Python 3 (maybe that's where the error comes from). I will fix this sometime this week, it's not very difficult.

Since I can't find the reference to urllib2 in my code right now, can you post the full error message and/or double check that it's not something in your own code? It's generally easy to fix this error:

http://stackoverflow.com/questions/2792650/python3-error-import-error-no-module-name-urllib2

**Comment by ruxi** [comment]
Hi Florian, that's great to hear.

Here is a gist including the error output:

[https://gist.github.com/ruxi/9cc75e6e5023306dc56f1fe71b1ca58f](https://gist.github.com/ruxi/9cc75e6e5023306dc56f1fe71b1ca58f)

**Comment by flo-compbio** [comment]
Thanks for the error output. I just pushed version 0.3.2 to pypi, which should work with python 3.

My recommendation would be to uninstall genometools first:

    pip uninstall genometools

And then install version 0.3.2

    pip install pyaffy==0.3.2

Please let me know if the new version works for you.
